name: mmm
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend # Name the container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
   container_name: database
   image: postgres:latest
   ports:
     - "5432:5432"
   environment:
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=postgres
       - POSTGRES_DB=postgres
   volumes:
     - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ../ # Define the build context as the current directory
      dockerfile: ./frontend/Dockerfile # Specify the Dockerfile to use for building the image
    container_name: frontend # Name the container
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ../nginx/certbot/conf/:/etc/letsencrypt/
    - ../nginx/certbot/www/:/var/www/certbot/

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ../nginx/certbot/conf/:/etc/letsencrypt/
      - ../nginx/certbot/www/:/var/www/certbot/
    command: certonly --webroot --webroot-path /var/www/certbot/ --force-renewal --email no-reply-test@ovh.net -d test.mmmenus.fr --agree-tos

volumes:
  pgdata:
